name = "synth"
version = "0.1.0"
license = "license"
author = "nonQualities"
maintainer = "ronit965choudhury@outlook.com"
copyright = "Copyright 2026, nonQualities"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
test = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

